version: 2
jobs:
  build:
    machine:
      image: circleci/classic:201708-01
    working_directory: ~/go/src/github.com/fnproject/ext-metrics
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GOPATH=/home/circleci/go
      - GOVERSION=1.9.1
      - OS=linux
      - ARCH=amd64
    steps:
      - checkout
  test-custom-executable:
    machine:
      image: circleci/classic:201708-01
    working_directory: ~/go/src/github.com/fnproject/ext-metrics
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GOPATH=/home/circleci/go
      - GOVERSION=1.9.1
      - OS=linux
      - ARCH=amd64
    steps:
      - run:
          name: Update go
          command: |
            go version
            go env GOROOT
            mkdir tmp
            cd tmp
            sudo rm -rf /usr/local/go
            wget https://storage.googleapis.com/golang/go$GOVERSION.$OS-$ARCH.tar.gz
            sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
            go version
      - run:
          name: Install glide
          command: |
            mkdir $GOPATH/bin
            export PATH=$GOPATH/bin:$PATH
            curl https://glide.sh/get | sh
      - run:
          name: Build demo extended Fn server
          command: |
            export PATH=$GOPATH/bin:$PATH
            glide install
            go build
      - run:
          name: Start demo extended Fn server (in the background)
          command: ./ext-metrics
          background: true
      - run:
          name: Update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
            docker version
      - run:
          name: Start Prometheus (in the background)
          command: docker run --name=prometheus -d -p 9090:9090 -v ${GOPATH}/src/github.com/fnproject/ext-metrics/examples/developers/prometheus.yml:/etc/prometheus/prometheus.yml --add-host="fnserver:`route | grep default | awk '{print $2}'`" prom/prometheus
      - run:
          name: Run tests on demo extended Fn server
          command: |
            sleep 5
            go test ./...
      - run:
           name: Terminate Prometheus
           command: |
             docker ps
             docker kill prometheus
             docker ps
      - run:
            name: Terminate demo extended Fn server 
            command: |
              ps -ef | grep "/ext-metrics" | grep -v grep
              ps -ef | grep "/ext-metrics" | grep -v grep | awk '{print "kill -9 " $2}' | sh
      - run:
            name: Install Fn CLI
            command: |
              curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh
  test-custom-image:
    machine:
      image: circleci/classic:201708-01
    working_directory: ~/go/src/github.com/fnproject/ext-metrics
    environment: # apparently expansion doesn't work here yet: https://discuss.circleci.com/t/environment-variable-expansion-in-working-directory/11322
      - GOPATH=/home/circleci/go
      - GOVERSION=1.9.1
      - OS=linux
      - ARCH=amd64
    steps:
      - run:
          name: Update go
          command: |
            go version
            go env GOROOT
            mkdir tmp
            cd tmp
            sudo rm -rf /usr/local/go
            wget https://storage.googleapis.com/golang/go$GOVERSION.$OS-$ARCH.tar.gz
            sudo tar -C /usr/local -xzf go$GOVERSION.$OS-$ARCH.tar.gz
            go version
      - run:
          name: Install glide
          command: |
            mkdir $GOPATH/bin
            export PATH=$GOPATH/bin:$PATH
            curl https://glide.sh/get | sh
      - run:
          name: Build demo extended Fn server
          command: |
            export PATH=$GOPATH/bin:$PATH
            glide install
            go build
      - run:
          name: Start demo extended Fn server (in the background)
          command: ./ext-metrics
          background: true
      - run:
          name: Update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
            docker version
      - run:
          name: Start Prometheus (in the background)
          command: docker run --name=prometheus -d -p 9090:9090 -v ${GOPATH}/src/github.com/fnproject/ext-metrics/examples/developers/prometheus.yml:/etc/prometheus/prometheus.yml --add-host="fnserver:`route | grep default | awk '{print $2}'`" prom/prometheus
      - run:
          name: Run tests on demo extended Fn server
          command: |
            sleep 5
            go test ./...
      - run:
           name: Terminate Prometheus
           command: |
             docker ps
             docker kill prometheus
             docker ps
      - run:
            name: Terminate demo extended Fn server 
            command: |
              ps -ef | grep "/ext-metrics" | grep -v grep
              ps -ef | grep "/ext-metrics" | grep -v grep | awk '{print "kill -9 " $2}' | sh
      - run:
            name: Install Fn CLI
            command: |
              curl -LSs https://raw.githubusercontent.com/fnproject/cli/master/install | sh 
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-custom-executable:
          requires:
            - build
      - test-custom-image:
          requires:
            - build

              